version: 2.1
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.6"
    steps:
      - checkout

      # Configure SSH key for GitHub access
      - run:
          name: Configure SSH Key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts

      - run:
          name: Run main.py
          command: python main.py

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.6"
    steps:
      - checkout
      - run:
          name: Run main-test.py
          command: python main-test.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires: [build]

