version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/python:3.10.2"
    key:
      fingerprint: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINEezkMkURUE8p6/CKWXg/5zO9Iho7eAD3hxQmU4NIsO motawakil.ali.90@gmail.com"
      type: ssh
    steps:
      - checkout
      - run: python main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/python:3.10.2"
    steps:
      - checkout
      - run: python main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build